project:
  type: website

website:
  title: "Ivan Jimenez Pineda Portfolio"
  site-url: "https://ivanjimenezpineda4.github.io" 
  navbar:
    background: "#E5A823"
    left:
      - href: index.qmd
        text: Home
      - href: professional_experience.qmd
        text: Professional Experience
      - href: engineering_projects.qmd
        text: Engineering Projects
      - href: microprocessor_projects.qmd
        text: Microprocessor Projects
      - href: blog.qmd
        text: Blog
      - href: Resources.qmd
        text: Resources
      - href: get_to_know_me.qmd
        text: Get to Know Me!

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true